services:
  - type: web
    name: sample-service-name
    env: python
    region: ohio
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    numInstances: 1
    envVars:
      - key: BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    plan: free
