"""Add type column to Post model

Revision ID: c972bc8150dc
Revises: 4387f4b9ebb1
Create Date: 2024-06-12 21:34:32.934253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c972bc8150dc'
down_revision = '4387f4b9ebb1'
branch_labels = None
depends_on = None


def upgrade():
    # Eliminar todos los registros existentes en la tabla post
    op.execute("DELETE FROM post")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('type')
    # ### end Alembic commands ###
