"""add fields to ContactRequest

Revision ID: fda4fee15057
Revises: 3e0a7960912c
Create Date: 2024-06-30 22:42:17.435983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda4fee15057'
down_revision = '3e0a7960912c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_constraint('contact_request_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('contact_request_receiver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('contact_request_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contact_request_post_id_fkey', 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('contact_request_receiver_id_fkey', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('contact_request_sender_id_fkey', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('message',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('approved_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
